

-------------Browser---------------

browser=chrome
#browser=firefox
#browser=edge
#browser=ie
#browser=safari

-------------Urls--------------------

#url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
#url=https://opensource-demo-test.orangehrmlive.com/web/index.php/auth/login

-------------FilePath-----------------

#dataFile=System.getProperty("user.dir")+"/datafiles/employee.xlsx"


